#!/bin/sh
set -eu

usage()
{
    echo "Usage:"
}

while getopts :rlsh: OPT
do
    case $OPT in
        l) RANDROPTION="--left-of eDP-1";
            ;;
        r) RANDROPTION="--right-of eDP-1";
	   ;;
	s) RANDROPTION="--same-as eDP-1";
            ;;
        h) usage
            ;;
        *) usage
           ;;
    esac
done

/usr/bin/xrandr --output DP-1 --mode 1024x768 ${RANDROPTION} 
/usr/bin/nitrogen --restore
