#!/bin/sh

set -e

mkdir -pv ${HOME}/Dropbox

[ -z "${UID}" ] && UID="$(id -u)"
[ -z "${GID}" ] && GID="$(id -g)"

# docker run -d --restart=always --name=dropbox \
docker run -ti --restart=always --name=dropbox \
       -e DBOX_UID=${UID} \
       -e DBOX_GID=${GID} \
       -v ${HOME}/Dropbox:/dbox/Dropbox \
       -v ${HOME}/.dropbox:/dbox/.dropbox \
       -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
       -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
       janeczku/dropbox
