#!/bin/bash
set -eu
kill $(pidof fcitx)

echo "sleep 1" && sleep 1

export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"

export LANG='ja_JP.UTF-8'

/usr/bin/fcitx -d
