#!/bin/sh
# Referrence: https://wiki.archlinux.org/index.php/Firefox_Ramdisk?redirect=no#Relocate_cache_only_to_RAM
set -eu

FFDIR="${HOME}/.mozilla/firefox"
INTERVAL="720"
VOLATILE=/dev/shm/xyz.default
PROFILE="37klf1cl.default"
FORCE="0"

usage()
{
    exit 0
}

ffsync()
{
    local mem=xyz.default

    set -efu

    cd ${FFDIR}

    ln -sfn ${VOLATILE} ${mem}

    if [ -f ${mem}/.unpacked ]; then
	rsync -avi --delete --exclude .unpacked ${FFDIR}/${mem}/ ${FFDIR}/${PROFILE}/
	echo "$0: batch sync" | logger
    else
	rsync -aq --delete ${FFDIR}/${PROFILE}/ ${FFDIR}/${mem}/
	touch ${FFDIR}/${mem}/.unpacked
	rsync -aq --delete --exclude .unpacked ${FFDIR}/${mem}/ ${FFDIR}/${PROFILE}/
	echo "$0: init sync" | logger
    fi
}

### Main
main()
{
    rm -f ${VOLATILE}/.unpacked
    mkdir -p -m0700 ${VOLATILE}

    while :
    do
	ffsync
	sleep ${INTERVAL}
    done
}

while getopts :f OPT
do
    case $OPT in
        f) FORCE="1"
           ;;
        *) usage
    esac
done

[ "${FORCE}" -eq 1 ] && { ffsync; exit 0; }
main
