#!/bin/sh
set -eux

usage()
{
    echo "Usage:"
}

RANDROPTION=""

while getopts :rloh: OPT
do
    case $OPT in
        o) RANDROPTION="--output eDP-1 --off"
            ;;
        l) RANDROPTION="--left-of eDP-1";
            ;;
        r) RANDROPTION="--right-of eDP-1";
           ;;
        h) usage
            ;;
        *) usage
            ;;
    esac
done

/usr/bin/xrandr --output HDMI-1 --auto ${RANDROPTION}
/usr/bin/nitrogen --restore
