#!/bin/sh
set -eu

usage()
{
    echo "Usage:"
}

RANDROPTION=""

while getopts :rloh: OPT
do
    case $OPT in
	o) RANDROPTION="--output LVDS1 --off"
	   ;;
        l) RANDROPTION="--left-of LVDS1";
            ;;
        r) RANDROPTION="--right-of LVDS1";
           ;;
        h) usage
            ;;
        *) usage
            ;;
    esac
done

/usr/bin/xrandr --output HDMI1 --mode 1920x1080 ${RANDROPTION}
/usr/bin/nitrogen --restore
exec xmobar -x1
