#!/bin/sh
set -eux

MUSIC_DIR="${HOME}/Music"
# MUSIC_DIR="${HOME}/ACDFuse/EAC"

mpc clear > /dev/null
printf "mpc clear: success.\n"
mpc update > /dev/null
printf "mpc update: success.\n"

for i in $(find ${MUSIC_DIR} -name "*.cue")
do
    mpc load "${i##${MUSIC_DIR}/}"
done

for i in $(find ${MUSIC_DIR} -name "*.mp3")
do
    mpc add "${i##${MUSIC_DIR}/}"
done
