#!/bin/sh
set -eu

### iptables
iptables -F
iptables -X
iptables -Z

### base
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

### loopback
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

### input
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 123 -j ACCEPT

### output
# icmp
iptables -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
# tcp
# iptables -A OUTPUT -p tcp --dport 20 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 21 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 43 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 10022 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8443 -j ACCEPT
# rsync
iptables -A OUTPUT -p tcp --dport 873 -j ACCEPT
# mail
iptables -A OUTPUT -p tcp --dport 465 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 587 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 993 -j ACCEPT
# rdp
iptables -A OUTPUT -p tcp --dport 3389 -j ACCEPT
# irc
iptables -A OUTPUT -p tcp --dport 6667 -j ACCEPT
# git
iptables -A OUTPUT -p tcp --dport 9418 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8118 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9050 -j ACCEPT
# other
iptables -A OUTPUT -p tcp --dport 8443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 10081 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 5000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8008 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8080 -j ACCEPT
# radiko
iptables -A OUTPUT -p tcp --dport 1935 -j ACCEPT 
# ubuntu ppa
iptables -A OUTPUT -p tcp --dport 11371 -j ACCEPT
# airtame
iptables -A OUTPUT -p tcp --dport 35482 -j ACCEPT

# FTP (passive)
iptables -A OUTPUT -p tcp --dport 1024: -m state --state ESTABLISHED,RELATED -j ACCEPT
# udp
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
# LINE (?)
iptables -A OUTPUT -p udp --sport 64000:64100 --dport 33434:33535 -j ACCEPT
# LOCAL
iptables -A OUTPUT -d 10.2.0.0/16 -j ACCEPT
iptables -A OUTPUT -d 10.3.0.0/16 -j ACCEPT

# LOG
# iptables -A OUTPUT -j LOG --log-prefix "DROP packets" --log-level debug

### modprobe
# if ip_conntrack_ftp is module
# modprobe ip_conntrack_ftp 

# save
iptables -L -n -v
/etc/init.d/iptables save
