#!/bin/sh
set -eux

usage()
{
    echo "Usage:"
    exit 1
}

RANDROPTION=""
MODE="2560x1440"
FB="2560x1440"

flag_parse()
{
    for i in $*
    do
        case $i in
            "--help"|"-h")
                usage
                ;;
            "--mode")
                MODE_OPTS="1"
                ;;
            *)
                [ ${MODE_OPTS} = "1" ] && MODE=$i && MODE_OPTS="0" && continue
                ;;
        esac
        shift
    done
}

while true
do
    if [ -n "$(pidof polybar)" ] ; then
        kill $(pidof polybar)
    else
        break
    fi
done

while true
do
    if [ -n "$(pidof compton)" ] ; then
        kill $(pidof compton)
    else
        break
    fi
done

flag_parse $@

bspc monitor eDP-1 -g ${MODE}+0+0

xrandr --fb ${FB} \
       --output eDP-1 --primary --mode ${MODE} --pos 0x0 --transform 1,0,0,0,1,0,0,0,1 \
       --output DP-1 --off

sleep 1s
nitrogen --restore

set +e
bspc desktop Desktop -r
set -e
