#!/bin/sh
set -eux

usage()
{
    echo "Usage:"
    exit 1
}

RANDROPTION=""
MODE="2560x1440"

flag_parse()
{
    for i in $*
    do
        case $i in
            "--help"|"-h")
                usage
                ;;
            "--mode")
                MODE_OPTS="1"
                ;;
            *)
                [ ${MODE_OPTS} = "1" ] && MODE=$i && MODE_OPTS="0" && continue
                ;;
        esac
        shift
    done
}

flag_parse $@
xrandr --fbmm ${MODE} --output eDP-1 --mode ${MODE} --output DP-1 --off
xrandr --fb 3840x2160
nitrogen --restore
