#!/bin/sh
set -eux

usage()
{
    echo "Usage:"
    exit 1
}

RANDROPTION=""
MODE="2560x1440"
FB="2560x2160"

flag_parse()
{
    for i in $*
    do
        case $i in
            "--help"|"-h")
                usage
                ;;
            "--mode")
                MODE_OPTS="1"
                ;;
            *)
                [ ${MODE_OPTS} = "1" ] && MODE=$i && MODE_OPTS="0" && continue
                ;;
        esac
        shift
    done
}

flag_parse $@
xrandr --output eDP-1 --mode ${MODE} --output DP-1 --off --pos 0x0
xrandr --fb ${FB} --output eDP-1 --pos 0x0 --transform 1,0,0,0,1,0,0,0,1
nitrogen --restore
kill -s HUP $(pidof spectrwm)
