#!/bin/sh
set -eu

xrandr --output HDMI-2 --off
xrandr --output HDMI-1 --off
xrandr --output eDP-1 --mode 2560x1440
nitrogen --restore

for i in $(pgrep xmobar)
do
    grep -e 'x[0-9]' /proc/$i/cmdline && kill -15 $i
done
