#!/bin/sh

set -eu

cdrdao read-cd --device /dev/sr0 --read-raw --paranoia-mode 3 --datadisc disc.bin disc.toc
cdrdao read-cd --device /dev/sr0 --read-raw --paranoia-mode 3 --datafile disc.bin disc.toc

eject

toc2cue ./disc.toc ./disc.cue
flac -6 -V --force-raw --sample-rate=44100 --channels=2 --bps=16 --endian=big --sign=signed -o ./disc.flac ./disc.bin
rm -fv ./disc.bin ./disc.toc

ALBUM="$(pygrace --custom --output file.cue ./disc.cue)"
rm -fv ./disc.cue
