#!/bin/sh
if [ "$1" = "mirror" ] ; then
    /usr/bin/mplayer tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0 -fps 15 -vf mirror
    exit 0
fi
/usr/bin/mplayer tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0 -fps 15
